#!/usr/bin/env node
import { createTimestamp, inspectTimestamp, upgradeTimestamp, verifyTimestamp } from './ots-manager.js';
import { processQueue } from './timestamp-queue.js';

const usage=`PasevSU OpenTimestamps CLI
  node cli.js stamp <file> [--calendar <url>] [--whitelist <url>] [--m <count>]
  node cli.js upgrade <file.ots> [--calendar <url>] [--whitelist <url>]
  node cli.js verify <file.ots> [--file <original> | --digest <hex>] [--ignore-bitcoin-node] [--explorer-url <url>]
  node cli.js info <file.ots> [--verbose]
  node cli.js queue [--dir <pending-directory>] [--watch] [--interval <seconds>]`;
function parseArguments(args){const positional=[],options={calendars:[]};for(let i=0;i<args.length;i++){const arg=args[i];if(['--help','-h'].includes(arg))options.help=true;else if(['--verbose','--ignore-bitcoin-node','--watch','--no-default-whitelist'].includes(arg)){const key=arg.slice(2).replace(/-([a-z])/g,(_,c)=>c.toUpperCase());options[key]=true} else if(['--file','--digest','--calendar','--whitelist','--timeout','--m','--explorer-url','--dir','--interval'].includes(arg)){const value=args[++i];if(!value||value.startsWith('--'))throw new Error(`Missing value for ${arg}`);switch(arg){case'--file':options.file=value;break;case'--digest':options.digest=value;break;case'--calendar':options.calendars.push(value);break;case'--whitelist':(options.whitelist||=[]).push(value);break;case'--timeout':options.timeout=Number(value);break;case'--m':options.m=Number(value);break;case'--explorer-url':options.esplora={...options.esplora,url:value};break;case'--dir':options.directory=value;break;case'--interval':options.interval=Number(value)}}else if(arg.startsWith('-'))throw new Error(`Unknown option: ${arg}`);else positional.push(arg)}if(!options.calendars.length)delete options.calendars;if(options.interval!==undefined&&(!Number.isFinite(options.interval)||options.interval<5))throw new Error('--interval must be at least 5 seconds.');return{positional,options}}
async function main(args=process.argv.slice(2)){const{positional,options}=parseArguments(args),[command,file,...extra]=positional;if(!command||options.help){console.log(usage);return}if(command==='queue'){if(file||extra.length)throw new Error(usage);const directory=options.directory;const run=async()=>{const result=await processQueue({directory});console.log(JSON.stringify(result,null,2));if(result.results.some(item=>item.status==='error'))process.exitCode=2};await run();if(options.watch){const interval=(options.interval||60)*1000;setInterval(()=>run().catch(error=>{console.error(`OTS queue: ${error.message}`);process.exitCode=1}),interval)}return}if(!file||extra.length)throw new Error(usage);let result;switch(command){case'stamp':result=await createTimestamp(file,options);break;case'upgrade':result=await upgradeTimestamp(file,options);break;case'verify':result=await verifyTimestamp(file,options);if(!result.verified)process.exitCode=2;break;case'info':result=inspectTimestamp(file,options);break;default:throw new Error(`Unknown command: ${command}\n${usage}`)}console.log(JSON.stringify(result,null,2))}
main().catch(error=>{console.error(`OTS error: ${error.message}`);process.exitCode=1});