'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process'),http=require('http'),https=require('https');
const OPENSSL='/usr/bin/openssl';
const now=()=>new Date().toISOString();
const cmd=(bin,args,opt={})=>new Promise(resolve=>cp.execFile(bin,args,{timeout:120000,maxBuffer:32*1024*1024,...opt},(error,stdout,stderr)=>resolve({ok:!error,code:error?.code??0,stdout:String(stdout||''),stderr:String(stderr||''),error:error?.message||null,command:[bin,...args]})));
const shaFile=(p,a='sha256')=>crypto.createHash(a).update(fs.readFileSync(p)).digest('hex');
const PROVIDERS={
 DFN:{id:'DFN',rootSha256:'3cdc2c9e9e5a36cb5888fd1796cb912f846253b682c1b32057532033510c7bb6',rootName:'DFN-Verein Community Root CA 2022'},
 DigiCert:{id:'DigiCert',rootSha256:'552f7bdcf1a7af9e6ce672017f4f12abf77240c78e761ac203d1d9d20ac89988',rootName:'DigiCert Trusted Root G4'}
};
function urlsFromText(text,kind){const lines=String(text).split(/\r?\n/);const out=[];for(let i=0;i<lines.length;i++){const l=lines[i];if(kind==='crl'&&!/CRL Distribution Points|Full Name|URI:/i.test(l))continue;if(kind==='ocsp'&&!/OCSP|Authority Information Access|URI:/i.test(l))continue;for(const m of l.matchAll(/URI:(https?:\/\/[^\s,]+)/ig))out.push(m[1]);for(const m of l.matchAll(/OCSP\s*-\s*URI:(https?:\/\/[^\s,]+)/ig))out.push(m[1])}return [...new Set(out)].filter(u=>kind==='crl'?/crl|\.crl(?:$|\?)/i.test(u):true)}
function download(url,dest,max=8*1024*1024){return new Promise(resolve=>{let u;try{u=new URL(url)}catch{return resolve({ok:false,error:'BAD_URL'})}if(!['http:','https:'].includes(u.protocol))return resolve({ok:false,error:'BAD_PROTOCOL'});const lib=u.protocol==='https:'?https:http;const q=lib.get({protocol:u.protocol,hostname:u.hostname,port:u.port||undefined,path:u.pathname+u.search,headers:{'User-Agent':'PasevSU-HA-Evidence/1.0-rc4'}},r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location){r.resume();return download(new URL(r.headers.location,u).toString(),dest,max).then(resolve)}if(r.statusCode<200||r.statusCode>=300){r.resume();return resolve({ok:false,status:r.statusCode,error:'HTTP_STATUS'})}let n=0;const chunks=[];r.on('data',c=>{n+=c.length;if(n>max)q.destroy(Error('download too large'));else chunks.push(c)});r.on('end',()=>{try{const b=Buffer.concat(chunks);fs.writeFileSync(dest,b);resolve({ok:true,status:r.statusCode,bytes:b.length,sha256:shaFile(dest)})}catch(e){resolve({ok:false,error:e.message})}})});q.on('error',e=>resolve({ok:false,error:e.message}));q.setTimeout(30000,()=>q.destroy(Error('timeout')))})}
async function certInfo(file){const r=await cmd(OPENSSL,['x509','-in',file,'-noout','-subject','-issuer','-serial','-dates','-fingerprint','-sha256','-ext','extendedKeyUsage','-ext','crlDistributionPoints','-ext','authorityInfoAccess']);const text=r.stdout+r.stderr;const get=re=>text.match(re)?.[1]?.trim()||null;return {ok:r.ok,file:path.basename(file),sha256:shaFile(file),subject:get(/subject=([^\n]+)/i),issuer:get(/issuer=([^\n]+)/i),serial:(get(/serial=([^\n]+)/i)||'').replace(/^0x/i,''),notBefore:get(/notBefore=([^\n]+)/i),notAfter:get(/notAfter=([^\n]+)/i),timeStamping:/Time Stamping/i.test(text),ekuCritical:/X509v3 Extended Key Usage:\s*critical/i.test(text),crlUrls:urlsFromText(text,'crl'),ocspUrls:urlsFromText(text,'ocsp'),raw:text}}
async function splitTokenCerts(tst,outdir){const pem=path.join(outdir,'RFC3161_CERTIFICATES.pem');const r=await cmd(OPENSSL,['pkcs7','-inform','DER','-in',tst,'-print_certs','-out',pem]);if(!r.ok)return {ok:false,result:r,certs:[]};const text=fs.readFileSync(pem,'utf8');const blocks=text.match(/-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/g)||[];const certs=[];for(let i=0;i<blocks.length;i++){const f=path.join(outdir,`RFC3161_CERT_${String(i+1).padStart(2,'0')}.pem`);fs.writeFileSync(f,blocks[i]+'\n');certs.push({file:f,info:await certInfo(f)})}return {ok:certs.length>0,result:r,pem,certs}}
async function findSigner(certs){for(const c of certs){if(c.info.timeStamping)return c}return certs[0]||null}
async function verifyChain(signer,certs,caFile,outdir){const others=certs.filter(c=>c.file!==signer.file);const untrusted=path.join(outdir,'RFC3161_UNTRUSTED_CHAIN.pem');fs.writeFileSync(untrusted,others.map(c=>fs.readFileSync(c.file,'utf8')).join('\n'));const args=['verify','-purpose','timestampsign','-show_chain','-CAfile',caFile];if(others.length)args.push('-untrusted',untrusted);args.push(signer.file);const r=await cmd(OPENSSL,args);fs.writeFileSync(path.join(outdir,'RFC3161_CHAIN_VERIFY.txt'),r.stdout+r.stderr);return {ok:r.ok,output:r.stdout+r.stderr,untrusted:others.length?path.basename(untrusted):null,result:r}}
async function rootPinPresent(caFile,expected,outdir){if(!expected||!fs.existsSync(caFile))return {ok:false,error:'NO_PIN_OR_CA'};const text=fs.readFileSync(caFile,'utf8');const blocks=text.match(/-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/g)||[];for(let i=0;i<blocks.length;i++){const tmp=`/tmp/pasevsu-ca-${process.pid}-${i}.pem`;try{fs.writeFileSync(tmp,blocks[i]);const r=await cmd(OPENSSL,['x509','-in',tmp,'-noout','-fingerprint','-sha256']);const fp=(r.stdout.match(/=([0-9A-F:]+)/i)?.[1]||'').replace(/:/g,'').toLowerCase();if(fp===expected.toLowerCase()){const pinned=path.join(outdir,'RFC3161_PINNED_ROOT.pem');fs.writeFileSync(pinned,blocks[i]+'\n');return {ok:true,sha256:fp,index:i,file:pinned}}}finally{try{fs.unlinkSync(tmp)}catch{}}}return {ok:false,error:'PINNED_ROOT_NOT_IN_CA_STORE'}}
async function validateCrl(signer,issuer,outdir,genTime=null){const urls=[...signer.info.crlUrls,...(issuer?.info?.crlUrls||[])];if(!urls.length)return {status:'UNAVAILABLE',reason:'NO_CRL_DISTRIBUTION_POINT'};for(let i=0;i<urls.length;i++){const f=path.join(outdir,`RFC3161_CRL_${i+1}.der`),dl=await download(urls[i],f);if(!dl.ok)continue;let info=await cmd(OPENSSL,['crl','-in',f,'-inform','DER','-noout','-text']);let inform='DER';if(!info.ok){info=await cmd(OPENSSL,['crl','-in',f,'-inform','PEM','-noout','-text']);inform='PEM'}if(!info.ok)continue;const sig=issuer?await cmd(OPENSSL,['crl','-in',f,'-inform',inform,'-noout','-verify','-CAfile',issuer.file]):{ok:false,error:'ISSUER_MISSING'};const serial=(signer.info.serial||'').replace(/^0+/,'').toUpperCase();const revoked=[...info.stdout.matchAll(/Serial Number:\s*([0-9A-F]+)/ig)].map(m=>m[1].replace(/^0+/,'').toUpperCase());const isRevoked=serial&&revoked.includes(serial);fs.writeFileSync(path.join(outdir,'RFC3161_CRL_VERIFY.txt'),(sig.stdout||'')+(sig.stderr||'')+`\nSigner serial: ${serial}\nRevoked: ${isRevoked}\n`);const thisUpdate=info.stdout.match(/Last Update:\s*([^\n]+)/i)?.[1]?.trim()||null,nextUpdate=info.stdout.match(/Next Update:\s*([^\n]+)/i)?.[1]?.trim()||null,gt=genTime?Date.parse(genTime):NaN,tu=thisUpdate?Date.parse(thisUpdate):NaN,nu=nextUpdate?Date.parse(nextUpdate):NaN,freshAtGenTime=Number.isFinite(gt)&&Number.isFinite(tu)&&Number.isFinite(nu)?(tu<=gt&&gt<=nu):false;return {status:isRevoked?'REVOKED':(sig.ok&&freshAtGenTime?'GOOD':'UNKNOWN'),url:urls[i],file:path.basename(f),sha256:shaFile(f),signatureVerified:!!sig.ok,serialChecked:serial,revoked:isRevoked,thisUpdate,nextUpdate,freshAtGenTime,raw:info.stdout}}
return {status:'UNAVAILABLE',reason:'CRL_DOWNLOAD_OR_PARSE_FAILED',urls}}
async function validateOcsp(signer,issuer,caFile,outdir){if(!issuer)return {status:'UNAVAILABLE',reason:'ISSUER_MISSING'};const url=signer.info.ocspUrls.find(x=>/^https?:/i.test(x));if(!url)return {status:'UNAVAILABLE',reason:'NO_OCSP_URI'};const req=path.join(outdir,'RFC3161_OCSP.req.der'),resp=path.join(outdir,'RFC3161_OCSP.der');const q=await cmd(OPENSSL,['ocsp','-issuer',issuer.file,'-cert',signer.file,'-reqout',req]);if(!q.ok)return {status:'UNAVAILABLE',reason:'OCSP_REQUEST_BUILD_FAILED',result:q};let u;try{u=new URL(url)}catch{return {status:'UNAVAILABLE',reason:'BAD_OCSP_URL'}};const args=['ocsp','-issuer',issuer.file,'-cert',signer.file,'-url',url,'-CAfile',caFile,'-respout',resp,'-timeout','30'];const r=await cmd(OPENSSL,args);fs.writeFileSync(path.join(outdir,'RFC3161_OCSP_VERIFY.txt'),r.stdout+r.stderr);const txt=r.stdout+r.stderr;let status=/:\s*good\b/i.test(txt)?'GOOD':(/:\s*revoked\b/i.test(txt)?'REVOKED':(r.ok?'UNKNOWN':'UNAVAILABLE'));return {status,url,file:fs.existsSync(resp)?path.basename(resp):null,sha256:fs.existsSync(resp)?shaFile(resp):null,signatureVerified:r.ok,output:txt,result:r}}
async function validate({tst,outdir,providerId,caFile='/etc/ssl/certs/ca-certificates.crt',genTime=null}){const provider=PROVIDERS[providerId]||null,split=await splitTokenCerts(tst,outdir);if(!split.ok)return {schema:'pasevsu-tsa-pki/v1',ok:false,stage:'certificate-extraction',split};const signer=await findSigner(split.certs);if(!signer)return {schema:'pasevsu-tsa-pki/v1',ok:false,stage:'signer-detection'};const issuer=split.certs.find(c=>c.file!==signer.file&&c.info.subject&&signer.info.issuer&&c.info.subject===signer.info.issuer)||split.certs.find(c=>c.file!==signer.file)||null;const pin=provider?await rootPinPresent(caFile,provider.rootSha256,outdir):{ok:false,error:'UNKNOWN_PROVIDER'};const chain=pin.ok?await verifyChain(signer,split.certs,pin.file,outdir):{ok:false,error:'PINNED_ROOT_UNAVAILABLE'};let validAtGenTime=null;if(genTime){const t=Date.parse(genTime),nb=Date.parse(signer.info.notBefore),na=Date.parse(signer.info.notAfter);if(Number.isFinite(t)&&Number.isFinite(nb)&&Number.isFinite(na))validAtGenTime=t>=nb&&t<=na}
const crl=await validateCrl(signer,issuer,outdir,genTime),ocsp=await validateOcsp(signer,issuer,caFile,outdir);const revoked=crl.status==='REVOKED'||ocsp.status==='REVOKED';const revocationGood=crl.status==='GOOD'||ocsp.status==='GOOD';const checks={signerCertificate:true,timeStampingEku:signer.info.timeStamping,ekuCritical:signer.info.ekuCritical,chainValidated:chain.ok,pinnedRoot:pin.ok,validAtGenTime,revocationValidated:revocationGood,revoked};const ok=!revoked&&checks.timeStampingEku&&checks.ekuCritical&&checks.chainValidated&&checks.pinnedRoot&&checks.validAtGenTime===true&&checks.revocationValidated;const result={schema:'pasevsu-tsa-pki/v1',createdAt:now(),ok,provider,signer:signer.info,issuer:issuer?.info||null,certificates:split.certs.map(c=>c.info),chain,pinnedRoot:pin,crl,ocsp,checks};fs.writeFileSync(path.join(outdir,'RFC3161_PKI_VALIDATION.json'),JSON.stringify(result,null,2));return result}
module.exports={validate,PROVIDERS};
