'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
function sha256(bytes){return crypto.createHash('sha256').update(bytes).digest('hex')}
function rootHash(days){const hash=crypto.createHash('sha256');hash.update('blockchain-archive/v1');for(const day of Object.keys(days).sort()){hash.update(day);hash.update(JSON.stringify(days[day].summary));for(const height of Object.keys(days[day].blocks).sort((a,b)=>Number(a)-Number(b))){const block=days[day].blocks[height];hash.update(height);hash.update(block.id);hash.update(String(block.timestamp));hash.update(block.merkle_root||'')}}return hash.digest('hex')}
class ManifestBuilder {
  constructor(archivePath,logger,{saveEveryNBlocks=100,maxArchiveSizeMB=2048,resume=true}={}){this.archivePath=path.resolve(archivePath);this.logger=logger;this.saveEveryNBlocks=saveEveryNBlocks;this.maxArchiveSizeMB=maxArchiveSizeMB;this._dirty=false;this.data=resume&&fs.existsSync(this.archivePath)?JSON.parse(fs.readFileSync(this.archivePath,'utf8')):{meta:{format:'blockchain-archive/v1',created:new Date().toISOString(),updated:new Date().toISOString(),dateRange:{},integrity:{},chainBreaks:[],reorgs:[]},global:{},days:{},index:{by_txid:{}}};this.data.meta??={};this.data.global??={};this.data.days??={};this.data.index??={by_txid:{}};this.data.index.by_txid??={}}
  setDateRange(start,end,startHeight,endHeight){this.data.meta.dateRange={start,end,startBlockHeight:startHeight,endBlockHeight:endHeight};this._dirty=true}
  setGlobal(key,value,hash){this.data.global[key]={value,sha256:hash,updatedAt:new Date().toISOString()};this._dirty=true}
  addBlock(block,txids=[],audit=null,extras=null,headerHex=null,otsInfo=null){if(!block||!Number.isSafeInteger(Number(block.height))||!block.id||!Number.isFinite(Number(block.timestamp)))throw new TypeError('Block requires a height, id, and timestamp.');const day=String(block.timestamp_iso||new Date(Number(block.timestamp)*1000).toISOString()).slice(0,10);const record= this.data.days[day]??={summary:{date:day,blocks:0,transactions:0},blocks:{},transactions:{}};const height=String(block.height);if(record.blocks[height])throw new Error(`Block ${height} already exists in archive.`);record.blocks[height]={...block,txids_count:Array.isArray(txids)?txids.length:0,audit,extras,header_hex:headerHex,ots:otsInfo};record.summary.blocks++;for(const txid of txids||[]){if(typeof txid!=='string'||!txid)continue;record.transactions[txid]={block_height:Number(block.height),block_id:block.id,timestamp:block.timestamp};this.data.index.by_txid[txid]={date:day,height:Number(block.height),block_id:block.id};record.summary.transactions++}this._dirty=true;if(this.saveEveryNBlocks>0&&Number(block.height)%this.saveEveryNBlocks===0)this.save()}
  save(){if(!this._dirty)return this.archivePath;this.data.meta.updated=new Date().toISOString();const bytes=Buffer.from(JSON.stringify(this.data,null,2)+'\n');const maxBytes=this.maxArchiveSizeMB*1024*1024;if(Number.isFinite(maxBytes)&&maxBytes>0&&bytes.length>maxBytes)throw new Error(`Archive exceeds configured maximum of ${this.maxArchiveSizeMB} MB.`);fs.mkdirSync(path.dirname(this.archivePath),{recursive:true});const temp=`${this.archivePath}.${process.pid}.tmp`;try{fs.writeFileSync(temp,bytes,{flag:'wx',mode:0o600});fs.renameSync(temp,this.archivePath);this._dirty=false;return this.archivePath}catch(error){try{fs.unlinkSync(temp)}catch{}throw error}}
  finalize(chainInfo={},extra={}){this.data.meta.dateRange??={};this.data.meta.dateRange.totalDays=Object.keys(this.data.days).length;this.data.meta.dateRange.totalBlocks=Object.values(this.data.days).reduce((sum,day)=>sum+Object.keys(day.blocks).length,0);const root=rootHash(this.data.days);this.data.meta.integrity={...(this.data.meta.integrity||{}),rootHash:root,chainValid:Boolean(chainInfo.valid),chainEntries:chainInfo.entries??0,chainLastHash:chainInfo.lastHash??null,chainFile:extra.logFiles?.chain??null,sessionLog:extra.logFiles?.session??null,otsFiles:extra.otsFiles??[],rootAlgorithm:'SHA-256'};this._dirty=true;this.save();const payload=fs.readFileSync(this.archivePath);const contentHash=sha256(payload);this.data.manifest={file:path.basename(this.archivePath),sizeMB:Number((payload.length/1024/1024).toFixed(4)),sha256:contentHash,generatedAt:new Date().toISOString(),generatedBy:'PasevSU ArchiveBuilder'};this._dirty=true;this.save();const finalBytes=fs.readFileSync(this.archivePath);const fileHash=sha256(finalBytes);const sidecar=`${fileHash}  ${path.basename(this.archivePath)}\n`;const sidecarPath=`${this.archivePath}.sha256`;const sidecarTemp=`${sidecarPath}.${process.pid}.tmp`;try{fs.writeFileSync(sidecarTemp,sidecar,{flag:'wx',mode:0o600});fs.renameSync(sidecarTemp,sidecarPath)}catch(error){try{fs.unlinkSync(sidecarTemp)}catch{}throw error}return{rootHash:root,fileHash,manifestHash:sha256(Buffer.from(JSON.stringify(this.data.manifest)))} }
}
module.exports={ManifestBuilder,rootHash};