'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process'),https=require('https');
const TSA=require('./tsa-engine');
const ROOT='/opt/pasevsu/app', PORT=8099;
const APP_VERSION=(()=>{try{return require('./package.json').version}catch{return 'UNKNOWN'}})();
const CASE_ROOT=process.env.CHRONOSEAL_EVIDENCE_ROOT||process.env.PASEVSU_OTS_ROOT||'/config/chronoseal/evidence';
const IMPORT_ROOT=process.env.CHRONOSEAL_IMPORT_ROOT||'/share/chronoseal/import';
const EXPORT_ROOT=process.env.CHRONOSEAL_EXPORT_ROOT||'/share/chronoseal/export';
const STAGING_ROOT=process.env.CHRONOSEAL_STAGING_ROOT||'/config/chronoseal/staging';
const AUTO_EXPORT=/^(1|true|yes|on)$/i.test(process.env.CHRONOSEAL_AUTO_EXPORT||'true');
const COPY_ORIGINAL=/^(1|true|yes|on)$/i.test(process.env.CHRONOSEAL_COPY_ORIGINAL||'true');
const IMPORT_RECURSIVE=/^(1|true|yes|on)$/i.test(process.env.CHRONOSEAL_IMPORT_RECURSIVE||'true');
const MAX_UPLOAD_BYTES=Math.max(1,Number(process.env.CHRONOSEAL_MAX_UPLOAD_MIB||1024))*1024*1024;
const CRYPTO=process.env.PASEVSU_CRYPTO_HOME||'/opt/pasevsu/_crypto';
const JS_OTS_CANDIDATES=[path.join(CRYPTO,'javascript-opentimestamps','ots-cli.js'),path.join('/opt/pasevsu/node_modules/opentimestamps','ots-cli.js')];
const JS_OTS=JS_OTS_CANDIDATES.find(x=>fs.existsSync(x))||JS_OTS_CANDIDATES[0];
const JSENCRYPT_DIR=path.join(CRYPTO,'jsencrypt');
const TS_OTS_DIR=path.join(CRYPTO,'typescript-opentimestamps');
const OPENPGP_DIR=path.join(CRYPTO,'openpgpjs');
const SYSTEM_CA='/etc/ssl/certs/ca-certificates.crt';
function buildTrustBundle(){const out='/tmp/pasevsu-ca-bundle.pem';let data='';try{data=fs.readFileSync(SYSTEM_CA,'utf8')}catch{}const d=path.join(CRYPTO,'trust');if(fs.existsSync(d)){for(const n of fs.readdirSync(d).sort()){if(!/\.(?:pem|crt|cer)$/i.test(n))continue;const f=path.join(d,n);if(!fs.statSync(f).isFile())continue;try{let t=fs.readFileSync(f,'utf8');if(/BEGIN CERTIFICATE/.test(t))data+='\n'+t;else{const r=cp.execFileSync('/usr/bin/openssl',['x509','-inform','DER','-in',f,'-outform','PEM'],{encoding:'utf8',stdio:['ignore','pipe','ignore']});data+='\n'+r}}catch{}}}fs.writeFileSync(out,data);return out}
const CA_BUNDLE=buildTrustBundle();
const JAVA_OTS_CANDIDATES=[path.join(CRYPTO,'java-opentimestamps','target','OtsCli.jar'),path.join(CRYPTO,'opentimestamps','OtsCli.jar')];
const RETRY_BASE_MS=Number(process.env.PASEVSU_OTS_RETRY_MS||15*60*1000), RETRY_MAX_MS=6*60*60*1000;
const TYPES={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.asc':'application/pgp-keys','.sig':'application/pgp-signature','.ots':'application/octet-stream','.tsq':'application/timestamp-query','.tsr':'application/timestamp-reply','.tst':'application/timestamp-token'};
for(const d of [CASE_ROOT,IMPORT_ROOT,EXPORT_ROOT,STAGING_ROOT]) fs.mkdirSync(d,{recursive:true});
const now=()=>new Date().toISOString(), exists=p=>{try{return fs.existsSync(p)}catch{return false}}, safeName=n=>String(n||'evidence.bin').replace(/[^A-Za-z0-9._-]+/g,'_').slice(0,180)||'evidence.bin';
const shaBuf=(b,a='sha256')=>crypto.createHash(a).update(b).digest('hex');
const shaFile=(p,a='sha256')=>{const h=crypto.createHash(a),fd=fs.openSync(p,'r'),buf=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n))}}finally{fs.closeSync(fd)}return h.digest('hex')};
const hashes=p=>({bytes:fs.statSync(p).size,sha256:shaFile(p),sha512:shaFile(p,'sha512')});
const writeJson=(p,o)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=p+'.tmp';fs.writeFileSync(t,JSON.stringify(o,null,2));fs.renameSync(t,p)};
const readJson=(p,d=null)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return d}};
const j=(res,code,obj)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj,null,2))};
const cmd=(bin,args,opt={})=>new Promise(resolve=>cp.execFile(bin,args,{timeout:180000,maxBuffer:16*1024*1024,...opt},(error,stdout,stderr)=>resolve({ok:!error,code:error?.code??0,stdout:String(stdout||''),stderr:String(stderr||''),error:error?.message||null,command:[bin,...args]})));
async function body(req,max=1024*1024*1024){return new Promise((ok,no)=>{let a=[],n=0,failed=false;req.on('data',c=>{if(failed)return;n+=c.length;if(n>max){failed=true;a=[];const e=Error('REQUEST_TOO_LARGE');e.statusCode=413;no(e);return}a.push(c)});req.on('end',()=>{if(!failed)ok(Buffer.concat(a))});req.on('error',e=>{if(!failed)no(e)})})}
async function streamHash(req,max=MAX_UPLOAD_BYTES){return new Promise((resolve,reject)=>{let bytes=0,failed=false;const h256=crypto.createHash('sha256'),h512=crypto.createHash('sha512');req.on('data',c=>{if(failed)return;bytes+=c.length;if(bytes>max){failed=true;const e=Error('REQUEST_TOO_LARGE');e.statusCode=413;reject(e);return}h256.update(c);h512.update(c)});req.on('end',()=>{if(!failed)resolve({bytes,sha256:h256.digest('hex'),sha512:h512.digest('hex')})});req.on('error',e=>{if(!failed)reject(e)})})}
async function streamToTemp(req,max=MAX_UPLOAD_BYTES){for(const d of [CASE_ROOT,IMPORT_ROOT,EXPORT_ROOT,STAGING_ROOT]) fs.mkdirSync(d,{recursive:true});const tmp=path.join(STAGING_ROOT,`.upload-${process.pid}-${Date.now()}-${crypto.randomBytes(8).toString('hex')}.tmp`);const fd=fs.openSync(tmp,'wx',0o600),h256=crypto.createHash('sha256'),h512=crypto.createHash('sha512');let bytes=0,failed=false;return new Promise((resolve,reject)=>{const fail=e=>{if(failed)return;failed=true;try{fs.closeSync(fd)}catch{};try{fs.unlinkSync(tmp)}catch{};reject(e)};req.on('data',c=>{if(failed)return;bytes+=c.length;if(bytes>max){const e=Error('REQUEST_TOO_LARGE');e.statusCode=413;return fail(e)}try{fs.writeSync(fd,c);h256.update(c);h512.update(c)}catch(e){fail(e)}});req.on('end',()=>{if(failed)return;try{fs.fsyncSync(fd);fs.closeSync(fd);resolve({tmp,bytes,sha256:h256.digest('hex'),sha512:h512.digest('hex')})}catch(e){fail(e)}});req.on('error',fail)})}
function fsyncDir(d){try{const fd=fs.openSync(d,'r');try{fs.fsyncSync(fd)}finally{fs.closeSync(fd)}}catch{}}
function atomicMoveNoReplace(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});try{fs.linkSync(src,dst);fs.unlinkSync(src)}catch(e){if(e.code==='EEXIST')throw e;throw e}fsyncDir(path.dirname(dst))}
function makeCaseFromTemp(name,up){const base=safeName(name),short=up.sha256.slice(0,12);let dir=path.join(CASE_ROOT,base);if(exists(dir)){const om=readJson(path.join(dir,'manifests','original_manifest.json'));if(om&&om.sha256!==up.sha256)dir=path.join(CASE_ROOT,`${base}__${short}`)}const p=casePaths(dir);for(const d of Object.values(p).filter(x=>x!==p.state))fs.mkdirSync(d,{recursive:true});const dst=path.join(p.original,base),incoming={bytes:up.bytes,sha256:up.sha256,sha512:up.sha512};if(exists(dst)){const old=hashes(dst);try{fs.unlinkSync(up.tmp)}catch{};if(old.sha256!==incoming.sha256||old.sha512!==incoming.sha512||old.bytes!==incoming.bytes)throw Error('CASE_NAME_HASH_COLLISION');return {dir,p,dst,base,evidenceId:`PSU-${short.toUpperCase()}`,original:old,reused:true}}atomicMoveNoReplace(up.tmp,dst);const written=hashes(dst);if(written.sha256!==incoming.sha256||written.sha512!==incoming.sha512||written.bytes!==incoming.bytes){try{fs.unlinkSync(dst)}catch{};throw Error('FORENSIC_BACKUP_HASH_MISMATCH')}try{fs.chmodSync(dst,0o444)}catch{};const evidenceId=`PSU-${short.toUpperCase()}`;writeJson(path.join(p.manifests,'original_manifest.json'),{schema:'pasevsu-original-manifest/v1',evidenceId,createdAt:now(),originalName:base,storedRelativePath:`original/${base}`,immutable:true,...written});audit(dir,'ORIGINAL_BACKUP_VERIFIED',{evidenceId,file:base,...written});return {dir,p,dst,base,evidenceId,original:written,reused:false}}

function casePaths(dir){return {root:dir,original:path.join(dir,'original'),ots:path.join(dir,'ots'),tsa:path.join(dir,'tsa'),signatures:path.join(dir,'signatures'),artifacts:path.join(dir,'artifacts'),manifests:path.join(dir,'manifests'),reports:path.join(dir,'reports'),audit:path.join(dir,'audit'),state:path.join(dir,'manifests','confirmation_state.json')}}
function makeCase(name,buffer){const base=safeName(name),short=shaBuf(buffer).slice(0,12);let dir=path.join(CASE_ROOT,base);if(exists(dir)){const om=readJson(path.join(dir,'manifests','original_manifest.json'));if(om&&om.sha256!==shaBuf(buffer))dir=path.join(CASE_ROOT,`${base}__${short}`)}const p=casePaths(dir);for(const d of Object.values(p).filter(x=>x!==p.state))fs.mkdirSync(d,{recursive:true});const dst=path.join(p.original,base);if(exists(dst)){const old=hashes(dst),incoming={bytes:buffer.length,sha256:shaBuf(buffer),sha512:shaBuf(buffer,'sha512')};if(old.sha256!==incoming.sha256||old.bytes!==incoming.bytes)throw Error('CASE_NAME_HASH_COLLISION');return {dir,p,dst,base,evidenceId:`PSU-${short.toUpperCase()}`,original:old,reused:true}}
 const fd=fs.openSync(dst,'wx');try{fs.writeFileSync(fd,buffer);fs.fsyncSync(fd)}finally{fs.closeSync(fd)};const written=hashes(dst),incoming={bytes:buffer.length,sha256:shaBuf(buffer),sha512:shaBuf(buffer,'sha512')};if(written.sha256!==incoming.sha256||written.sha512!==incoming.sha512||written.bytes!==incoming.bytes){try{fs.unlinkSync(dst)}catch{};throw Error('FORENSIC_BACKUP_HASH_MISMATCH')}
 try{fs.chmodSync(dst,0o444)}catch{};const evidenceId=`PSU-${short.toUpperCase()}`;writeJson(path.join(p.manifests,'original_manifest.json'),{schema:'pasevsu-original-manifest/v1',evidenceId,createdAt:now(),originalName:base,storedRelativePath:`original/${base}`,immutable:true,...written});audit(dir,'ORIGINAL_BACKUP_VERIFIED',{evidenceId,file:base,...written});return {dir,p,dst,base,evidenceId,original:written,reused:false}}
function audit(dir,event,data={}){const p=casePaths(dir),f=path.join(p.audit,'events.jsonl');fs.mkdirSync(p.audit,{recursive:true});let seq=1,previousHash='0'.repeat(128);try{const lines=fs.readFileSync(f,'utf8').trim().split(/\n/).filter(Boolean);if(lines.length){const last=JSON.parse(lines[lines.length-1]);seq=Number(last.sequence||lines.length)+1;previousHash=String(last.eventHash||previousHash)}}catch{}const core={schema:'pasevsu-audit-chain/SHA-512-CHAIN-V1',sequence:seq,ts:now(),event,...data,previousHash};const eventHash=shaBuf(Buffer.from(canonicalJson(core),'utf8'),'sha512'),rec={...core,eventHash};fs.appendFileSync(f,JSON.stringify(rec)+'\n');return rec}
function verifyAuditChain(dir){const f=path.join(casePaths(dir).audit,'events.jsonl');if(!exists(f))return {ok:true,events:0,head:null};const lines=fs.readFileSync(f,'utf8').split(/\n/).filter(Boolean);let prev='0'.repeat(128);for(let i=0;i<lines.length;i++){let r;try{r=JSON.parse(lines[i])}catch{return {ok:false,error:'AUDIT_JSON_INVALID',line:i+1}}const got=r.eventHash;const core={...r};delete core.eventHash;if(r.previousHash!==prev)return {ok:false,error:'AUDIT_PREVIOUS_HASH_MISMATCH',line:i+1};const exp=shaBuf(Buffer.from(canonicalJson(core),'utf8'),'sha512');if(got!==exp)return {ok:false,error:'AUDIT_EVENT_HASH_MISMATCH',line:i+1};prev=got}return {ok:true,events:lines.length,head:prev}}
function inventory(dir){const p=casePaths(dir),out=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(!f.endsWith('.tmp'))out.push({path:path.relative(dir,f).replace(/\\/g,'/'),...hashes(f)})}}walk(dir);out.sort((a,b)=>a.path.localeCompare(b.path));return out}
function snapshotManifest(dir){const orig=readJson(path.join(dir,'manifests','original_manifest.json'),{}),state=readJson(path.join(dir,'manifests','confirmation_state.json'),{});return {schema:'pasevsu-evidence-manifest/v2',evidenceId:orig.evidenceId||null,generatedAt:now(),original:orig,confirmation:state,artifacts:inventory(dir).filter(x=>!x.path.endsWith('final_manifest.json'))}}
function refreshManifest(dir){const m=snapshotManifest(dir);writeJson(path.join(dir,'manifests','working_manifest.json'),m);return m}
function probeCommand(bin,args,timeout=15000){try{const r=cp.spawnSync(bin,args,{encoding:'utf8',timeout,maxBuffer:4*1024*1024});return {ok:r.status===0,status:r.status,signal:r.signal||null,stdout:String(r.stdout||''),stderr:String(r.stderr||''),error:r.error?.message||null}}catch(e){return {ok:false,status:null,error:e.message,stdout:'',stderr:''}}}
function otsRuntime(){const jar=JAVA_OTS_CANDIDATES.find(exists);const candidates=[];for(const entry of JS_OTS_CANDIDATES){if(!exists(entry))continue;const probe=probeCommand(process.execPath,[entry,'--help']);candidates.push({engine:entry.startsWith(CRYPTO)?'javascript-opentimestamps-source':'javascript-opentimestamps-npm',runtime:'node',entry,probe});if(probe.ok)return {ready:true,...candidates[candidates.length-1]}}if(jar){const probe=probeCommand('/usr/bin/java',['-jar',jar,'--help']);candidates.push({engine:'java-opentimestamps',runtime:'java',entry:jar,probe});if(probe.ok)return {ready:true,...candidates[candidates.length-1]}}return {ready:false,engine:null,detail:'No executable OTS engine passed its runtime probe',candidates}}
async function otsRun(action,original,otsFile){const r=otsRuntime();if(!r.ready)return {ok:false,error:'OTS_RUNTIME_MISSING',runtime:r};let bin,args;if(r.runtime==='node'){bin=process.execPath;args=action==='info'?[r.entry,'info','-v',otsFile]:[r.entry,action,action==='stamp'?original:otsFile]}else{bin='/usr/bin/java';args=['-jar',r.entry,action,action==='stamp'?original:otsFile]};const x=await cmd(bin,args,{cwd:path.dirname(original)});return {...x,engine:r.engine}}
function parseAttestations(text){text=String(text||'');const heights=[...text.matchAll(/BitcoinBlockHeaderAttestation\((\d+)\)/g)].map(m=>Number(m[1]));const verifyHeights=[...text.matchAll(/(?:Bitcoin[^\n]*?(?:block\s*(?:height)?|height)[^0-9]{0,12})(\d{5,})/ig)].map(m=>Number(m[1]));const pending=[...text.matchAll(/PendingAttestation\(['\"]([^'\"]+)['\"]\)/g)].map(m=>m[1]);return {bitcoinBlockHeights:[...new Set([...heights,...verifyHeights])],pendingCalendars:[...new Set(pending)],timestampComplete:/Success!\s*Timestamp complete/i.test(text)}}
async function independentOtsVerify(original,otsFile){
 const results=[];
 const primary=otsRuntime();
 const jar=JAVA_OTS_CANDIDATES.find(exists);
 if(jar && primary.entry!==jar){const info=await cmd('/usr/bin/java',['-jar',jar,'info','-v',otsFile],{cwd:path.dirname(original)}),verify=await cmd('/usr/bin/java',['-jar',jar,'verify',otsFile],{cwd:path.dirname(original)});const parsed=parseAttestations(`${info.stdout}\n${info.stderr}\n${verify.stdout}\n${verify.stderr}`);results.push({engine:'java-opentimestamps',available:true,confirmed:verify.ok&&parsed.bitcoinBlockHeights.length>0,parsed,info,verify})}
 return {available:results.length>0,engines:results,allAvailableEnginesConfirm:results.length?results.every(x=>x.confirmed):null};
}
async function inspectConfirmation(original,otsFile){const adjacent=otsFile.slice(0,-4);let made=false;try{if(!exists(adjacent)){fs.copyFileSync(original,adjacent);made=true}const info=await otsRun('info',original,otsFile),verify=await otsRun('verify',original,otsFile),parsed=parseAttestations(`${info.stdout}\n${info.stderr}\n${verify.stdout}\n${verify.stderr}`),cross=await independentOtsVerify(original,otsFile);const primaryConfirmed=parsed.bitcoinBlockHeights.length>0&&verify.ok;const redundancyStatus=cross.available?(cross.allAvailableEnginesConfirm?'VERIFIED':'FAILED'):'NOT_AVAILABLE';const confirmed=primaryConfirmed&&(redundancyStatus!=='FAILED');return {confirmed,primaryConfirmed,redundancyStatus,parsed,info,verify,crossVerification:cross,checkedAt:now()}}finally{if(made)try{fs.unlinkSync(adjacent)}catch{}}}
function nextDelay(attempt){return Math.min(RETRY_MAX_MS,RETRY_BASE_MS*Math.pow(2,Math.min(Math.max(attempt-1,0),5)))}
function saveState(dir,s){s.updatedAt=now();writeJson(casePaths(dir).state,s);refreshManifest(dir);return s}
async function confirmationCycle(dir,manual=false){const p=casePaths(dir),origM=readJson(path.join(p.manifests,'original_manifest.json'));if(!origM)return {ok:false,error:'ORIGINAL_MANIFEST_MISSING'};const original=path.join(p.original,origM.originalName),otsFile=path.join(p.ots,origM.originalName+'.ots');if(!exists(original))return {ok:false,error:'ORIGINAL_MISSING'};if(!exists(otsFile))return {ok:false,error:'OTS_PROOF_NOT_FOUND'};let s=readJson(p.state,{schema:'pasevsu-ots-confirmation-state/v1',evidenceId:origM.evidenceId,state:'CREATED',attempt:0,createdAt:now()});if(s.state==='BLOCKCHAIN_VERIFIED')return s;if(!manual&&s.nextAttemptAt&&Date.parse(s.nextAttemptAt)>Date.now())return s;s.attempt=(s.attempt||0)+1;s.state='UPGRADE_ATTEMPTED';s.lastAttemptAt=now();audit(dir,'OTS_UPGRADE_ATTEMPT',{attempt:s.attempt});const before=hashes(otsFile);const backup=path.join(p.ots,`history_${String(s.attempt).padStart(4,'0')}_${before.sha256.slice(0,12)}.ots`);fs.copyFileSync(otsFile,backup);const up=await otsRun('upgrade',original,otsFile);const after=exists(otsFile)?hashes(otsFile):null;writeJson(path.join(p.ots,`upgrade_${String(s.attempt).padStart(4,'0')}.json`),{at:now(),before,after,result:up});const check=await inspectConfirmation(original,otsFile);writeJson(path.join(p.ots,`verify_${String(s.attempt).padStart(4,'0')}.json`),check);s.lastUpgrade={ok:up.ok,beforeSha256:before.sha256,afterSha256:after?.sha256||null};if(after)s.ots={file:`ots/${path.basename(otsFile)}`,...after};s.lastVerification={ok:check.verify.ok,bitcoinBlockHeights:check.parsed.bitcoinBlockHeights,pendingCalendars:check.parsed.pendingCalendars};if(check.confirmed){s.state='BLOCKCHAIN_VERIFIED';s.confirmedAt=now();s.blockchain={network:'bitcoin',blockHeights:check.parsed.bitcoinBlockHeights};s.nextAttemptAt=null;delete s.lastError;writeJson(path.join(p.ots,'blockchain_confirmation.json'),{schema:'pasevsu-blockchain-confirmation/v1',evidenceId:s.evidenceId,confirmedAt:s.confirmedAt,...s.blockchain,verification:check});audit(dir,'OTS_BLOCKCHAIN_VERIFIED',{attempt:s.attempt,blockHeights:check.parsed.bitcoinBlockHeights})}else{s.state=up.ok?'VERIFY_PENDING':'UPGRADE_RETRY_REQUIRED';s.lastError=up.ok?(check.verify.error||check.verify.stderr||'Blockchain attestation not yet confirmed'):(up.error||up.stderr||'Upgrade failed');s.nextAttemptAt=new Date(Date.now()+nextDelay(s.attempt)).toISOString();audit(dir,'OTS_CONFIRMATION_PENDING',{attempt:s.attempt,nextAttemptAt:s.nextAttemptAt,error:s.lastError})}return saveState(dir,s)}
async function upgradeCase(dir){const p=casePaths(dir),orig=readJson(path.join(p.manifests,'original_manifest.json'));if(!orig)return {ok:false,error:'ORIGINAL_MANIFEST_MISSING'};const original=path.join(p.original,orig.originalName),otsFile=path.join(p.ots,orig.originalName+'.ots');if(!exists(original))return {ok:false,error:'ORIGINAL_MISSING'};if(!exists(otsFile))return {ok:false,error:'OTS_PROOF_NOT_FOUND'};const before=hashes(otsFile),backup=path.join(p.ots,`manual_backup_${Date.now()}_${before.sha256.slice(0,12)}.ots`);fs.copyFileSync(otsFile,backup);const primary=await otsRun('upgrade',original,otsFile);let fallback=null;if(!primary.ok){const jar=JAVA_OTS_CANDIDATES.find(exists);if(jar){fallback=await cmd('/usr/bin/java',['-jar',jar,'upgrade',otsFile],{cwd:path.dirname(original)})}}const ok=primary.ok||fallback?.ok===true,after=exists(otsFile)?hashes(otsFile):null;const rec={ok,before,after,backup:path.basename(backup),primary,fallback,at:now()};writeJson(path.join(p.ots,`manual_upgrade_${Date.now()}.json`),rec);audit(dir,ok?'OTS_MANUAL_UPGRADE_OK':'OTS_MANUAL_UPGRADE_FAILED',{primaryOk:primary.ok,fallbackOk:fallback?.ok===true});const st=readJson(p.state);if(st&&after){st.ots={file:`ots/${path.basename(otsFile)}`,...after};st.lastManualUpgrade={ok,at:rec.at};saveState(dir,st)}else refreshManifest(dir);return rec}
async function verifyCase(dir){const p=casePaths(dir),orig=readJson(path.join(p.manifests,'original_manifest.json'));if(!orig)return {ok:false,error:'ORIGINAL_MANIFEST_MISSING'};const original=path.join(p.original,orig.originalName),otsFile=path.join(p.ots,orig.originalName+'.ots');if(!exists(original))return {ok:false,error:'ORIGINAL_MISSING'};if(!exists(otsFile))return {ok:false,error:'OTS_PROOF_NOT_FOUND'};const r=await inspectConfirmation(original,otsFile);const out={ok:r.verify.ok===true,blockchainVerified:r.confirmed===true,...r};writeJson(path.join(p.ots,`manual_verify_${Date.now()}.json`),out);audit(dir,out.ok?'OTS_MANUAL_VERIFY_OK':'OTS_MANUAL_VERIFY_FAILED',{blockchainVerified:out.blockchainVerified,heights:r.parsed.bitcoinBlockHeights});refreshManifest(dir);return out}
const caseLocks=new Map();async function withCaseLock(dir,fn){const k=path.resolve(dir);if(caseLocks.has(k))return {ok:false,error:'CASE_BUSY_RETRY'};caseLocks.set(k,true);try{return await fn()}finally{caseLocks.delete(k)}}
let workerBusy=false;async function worker(){if(workerBusy)return;workerBusy=true;try{for(const name of fs.readdirSync(CASE_ROOT)){const d=path.join(CASE_ROOT,name);if(!fs.statSync(d).isDirectory()||isSealed(d))continue;const s=readJson(casePaths(d).state);if(s&&s.state!=='BLOCKCHAIN_VERIFIED')await withCaseLock(d,()=>confirmationCycle(d,false))}}catch(e){console.error('OTS worker:',e)}finally{workerBusy=false}}
function storageStatus(){const one=p=>{try{const st=fs.statSync(p);fs.accessSync(p,fs.constants.R_OK|fs.constants.W_OK);return {path:p,exists:true,directory:st.isDirectory(),readable:true,writable:true}}catch(e){return {path:p,exists:exists(p),directory:false,readable:false,writable:false,error:e.code||e.message}}};return {evidence:one(CASE_ROOT),import:one(IMPORT_ROOT),export:one(EXPORT_ROOT),staging:one(STAGING_ROOT),autoExport:AUTO_EXPORT,copyOriginal:COPY_ORIGINAL,importRecursive:IMPORT_RECURSIVE,maxUploadBytes:MAX_UPLOAD_BYTES}}
function status(){const o=otsRuntime();const je=exists(path.join(JSENCRYPT_DIR,'package.json')),ts=exists(path.join(TS_OTS_DIR,'package.json')),op=exists(path.join(OPENPGP_DIR,'package.json')),jar=JAVA_OTS_CANDIDATES.find(exists);return {service:'PasevSU ChronoSeal Vault Backend',product:'PasevSU ChronoSeal Vault',version:APP_VERSION,caseRoot:CASE_ROOT,storage:storageStatus(),runtimes:{node:{ready:true,version:process.version},openssl:{ready:exists('/usr/bin/openssl')},ots:o,otsIndependent:{java:{ready:!!jar,entry:jar||null},typescriptSource:{ready:ts,source:ts?TS_OTS_DIR:null,note:'source detected; not executed unless a supported built CLI is supplied'}},openpgpSource:{ready:exists(path.join(ROOT,'app','vendor','openpgp.min.js')),source:op?OPENPGP_DIR:null,note:op?'source present; READY requires generated browser runtime':'source absent'},jsencrypt:{ready:je,source:je?JSENCRYPT_DIR:null},tsaPki:{ready:exists('/usr/bin/openssl')&&exists(CA_BUNDLE),strict:true}},worker:{persistent:true,baseRetryMs:RETRY_BASE_MS,maxRetryMs:RETRY_MAX_MS},network:{hostPortsConfigured:false,ingressRequiredByConfig:true,ingressOriginVerified:'NOT_ASSERTED_BY_BACKEND'},time:now()}}
async function postBinary(target,payload,ctype){return new Promise(resolve=>{let u;try{u=new URL(target)}catch{return resolve({ok:false,error:'INVALID_TSA_URL'})}if(!['https:','http:'].includes(u.protocol))return resolve({ok:false,error:'UNSUPPORTED_TSA_PROTOCOL'});const lib=u.protocol==='https:'?https:http,r=lib.request({protocol:u.protocol,hostname:u.hostname,port:u.port||undefined,path:u.pathname+u.search,method:'POST',headers:{'Content-Type':ctype,'Accept':'application/timestamp-reply','Content-Length':payload.length,'User-Agent':'PasevSU-HA-Evidence/1.0'}},resp=>{const chunks=[];resp.on('data',c=>chunks.push(c));resp.on('end',()=>resolve({ok:resp.statusCode>=200&&resp.statusCode<300,status:resp.statusCode,body:Buffer.concat(chunks),contentType:resp.headers['content-type']||''}))});r.on('error',e=>resolve({ok:false,error:e.message}));r.setTimeout(30000,()=>r.destroy(Error('TSA timeout')));r.end(payload)})}
async function tsaStamp(file,providerUrl,outdir,label){if(!providerUrl)return {ok:false,error:'TSA_URL_REQUIRED'};fs.mkdirSync(outdir,{recursive:true});const q=path.join(outdir,`${label}.tsq`),r=path.join(outdir,`${label}.tsr`),txt=path.join(outdir,`${label}_response.txt`);let x=await cmd('/usr/bin/openssl',['ts','-query','-data',file,'-sha256','-cert','-out',q]);if(!x.ok)return {ok:false,stage:'query',...x};const raw=fs.readFileSync(q),net=await postBinary(providerUrl,raw,'application/timestamp-query');if(!net.ok)return {ok:false,stage:'request',...net};fs.writeFileSync(r,net.body);x=await cmd('/usr/bin/openssl',['ts','-reply','-in',r,'-text']);fs.writeFileSync(txt,x.stdout+x.stderr);const token=path.join(outdir,`${label}.tst`),tok=await cmd('/usr/bin/openssl',['ts','-reply','-in',r,'-token_out','-out',token]);return {ok:x.ok&&tok.ok,providerUrl,httpStatus:net.status,query:path.basename(q),response:path.basename(r),token:tok.ok?path.basename(token):null,text:path.basename(txt),querySha256:shaFile(q),responseSha256:shaFile(r),openssl:x.stdout||x.stderr,tokenError:tok.ok?null:tok.stderr}}

function isSealed(dir){return exists(path.join(casePaths(dir).manifests,'SEALED.json'))}
function assertWritable(dir){if(isSealed(dir)){const e=Error('CASE_SEALED_IMMUTABLE');e.statusCode=423;throw e}}
function stableEvidenceInventory(dir){return inventory(dir).filter(x=>!['audit/events.jsonl','manifests/working_manifest.json','manifests/final_manifest.json','manifests/SEALED.json'].includes(x.path)&&!x.path.startsWith('manifests/manual_'))}
function verifyPhysicalArtifacts(dir,items){const mismatches=[];for(const item of items||[]){const rel=String(item.path||'').replace(/\\/g,'/');if(!rel||rel.includes('..')||rel.startsWith('/')){mismatches.push({path:rel,error:'INVALID_PATH'});continue}const f=path.resolve(dir,rel);if(!f.startsWith(path.resolve(dir)+path.sep)||!exists(f)||!fs.statSync(f).isFile()){mismatches.push({path:rel,error:'MISSING'});continue}const got=hashes(f);if(got.bytes!==item.bytes||got.sha256!==item.sha256||got.sha512!==item.sha512)mismatches.push({path:rel,error:'HASH_OR_SIZE_MISMATCH',expected:{bytes:item.bytes,sha256:item.sha256,sha512:item.sha512},actual:got})}return {ok:mismatches.length===0,checked:(items||[]).length,mismatches}}

async function strictPreflight(dir){
 const p=casePaths(dir),orig=readJson(path.join(p.manifests,'original_manifest.json'),{}),state=readJson(p.state,{});
 const original=path.join(p.original,orig.originalName||''),otsFile=path.join(p.ots,(orig.originalName||'')+'.ots');
 if(!orig.originalName||!exists(original))return {ok:false,error:'ORIGINAL_MISSING'};
 const oh=hashes(original);if(oh.bytes!==orig.bytes||oh.sha256!==orig.sha256||oh.sha512!==orig.sha512)return {ok:false,error:'ORIGINAL_INTEGRITY_MISMATCH',expected:orig,actual:oh};
 if(!exists(otsFile))return {ok:false,error:'OTS_PROOF_NOT_FOUND'};
 const ots=await inspectConfirmation(original,otsFile);if(!ots.primaryConfirmed)return {ok:false,error:'OTS_FRESH_VERIFICATION_FAILED',ots};
 if(state.state!=='BLOCKCHAIN_VERIFIED')return {ok:false,error:'OTS_STATE_NOT_BLOCKCHAIN_VERIFIED',ots,state:state.state||null};
 const startRec=readJson(path.join(p.tsa,'START','START.json'),{}),stopRec=readJson(path.join(p.tsa,'STOP','STOP.json'),{});
 const startInput=path.join(p.manifests,'canonical_evidence_manifest.json'),stopInput=path.join(p.manifests,'closing_digest.json');
 if(!startRec.validation?.ok||!stopRec.validation?.ok)return {ok:false,error:'TSA_VERIFIED_RECORDS_REQUIRED'};
 const start=await TSA.validateExisting({input:startInput,outdir:path.join(p.tsa,'START'),label:'RFC3161_START',providerId:'DFN',caFile:CA_BUNDLE});
 if(!start.ok)return {ok:false,error:'START_TSA_FRESH_REVALIDATION_FAILED',start};
 const stop=await TSA.validateExisting({input:stopInput,outdir:path.join(p.tsa,'STOP'),label:'RFC3161_STOP',providerId:'DigiCert',caFile:CA_BUNDLE});
 if(!stop.ok)return {ok:false,error:'STOP_TSA_FRESH_REVALIDATION_FAILED',start,stop};
 const auditCheck=verifyAuditChain(dir);if(!auditCheck.ok)return {ok:false,error:'AUDIT_CHAIN_INVALID',audit:auditCheck};
 return {ok:true,original:oh,ots,start,stop,audit:auditCheck,redundancyStatus:ots.redundancyStatus};
}
function copyFileVerified(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});if(exists(dst)){const a=hashes(src),b=hashes(dst);if(a.bytes===b.bytes&&a.sha256===b.sha256&&a.sha512===b.sha512)return {ok:true,idempotent:true,...b};throw Error('EXPORT_DESTINATION_COLLISION')}const tmp=dst+'.tmp-'+process.pid+'-'+Date.now();fs.copyFileSync(src,tmp,fs.constants.COPYFILE_EXCL);const a=hashes(src),b=hashes(tmp);if(a.bytes!==b.bytes||a.sha256!==b.sha256||a.sha512!==b.sha512){try{fs.unlinkSync(tmp)}catch{};throw Error('EXPORT_COPY_HASH_MISMATCH')}try{const fd=fs.openSync(tmp,'r');fs.fsyncSync(fd);fs.closeSync(fd)}catch{};fs.renameSync(tmp,dst);fsyncDir(path.dirname(dst));return {ok:true,idempotent:false,...b}}
function safeImportPath(rel){const clean=String(rel||'').replace(/\\/g,'/').replace(/^\/+/,''),root=path.resolve(IMPORT_ROOT),full=path.resolve(root,clean);if(!clean||full===root||!full.startsWith(root+path.sep))return null;try{const realRoot=fs.realpathSync(root),real=fs.realpathSync(full);if(real===realRoot||!real.startsWith(realRoot+path.sep))return null;return real}catch{return null}}
function listImportFiles(){const out=[],root=path.resolve(IMPORT_ROOT);function walk(d,depth){for(const ent of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const full=path.join(d,ent.name),rel=path.relative(root,full).split(path.sep).join('/');if(ent.isSymbolicLink())continue;if(ent.isDirectory()){if(IMPORT_RECURSIVE)walk(full,depth+1);continue}if(!ent.isFile())continue;const st=fs.statSync(full);out.push({relativePath:rel,name:ent.name,bytes:st.size,modifiedAt:st.mtime.toISOString()})}}walk(root,0);return out}
function importFileToCase(rel){const src=safeImportPath(rel);if(!src||!exists(src)||!fs.statSync(src).isFile())return {ok:false,error:'IMPORT_FILE_NOT_FOUND'};const st=fs.statSync(src);if(st.size>MAX_UPLOAD_BYTES)return {ok:false,error:'IMPORT_FILE_TOO_LARGE',bytes:st.size,maxBytes:MAX_UPLOAD_BYTES};const h=hashes(src),tmp=path.join(STAGING_ROOT,`.import-${process.pid}-${Date.now()}-${crypto.randomBytes(8).toString('hex')}.tmp`);fs.copyFileSync(src,tmp,fs.constants.COPYFILE_EXCL);const fd=fs.openSync(tmp,'r');try{fs.fsyncSync(fd)}finally{fs.closeSync(fd)}const copied=hashes(tmp);if(copied.bytes!==h.bytes||copied.sha256!==h.sha256||copied.sha512!==h.sha512){try{fs.unlinkSync(tmp)}catch{};return {ok:false,error:'IMPORT_STAGING_HASH_MISMATCH'}}const c=makeCaseFromTemp(path.basename(src),{tmp,...copied});audit(c.dir,'IMPORTED_FROM_CONFIGURED_ROOT',{relativePath:String(rel),source:{...h},stagedVerified:true});refreshManifest(c.dir);return {ok:true,case:path.basename(c.dir),evidenceId:c.evidenceId,sourceRelativePath:String(rel),original:c.original,reused:c.reused}}
function exportSealedCase(dir){const seal=verifySeal(dir);if(!seal.ok)return {ok:false,error:'SOURCE_SEAL_INVALID',verification:seal};const caseName=path.basename(dir),target=path.join(EXPORT_ROOT,caseName);fs.mkdirSync(target,{recursive:true});const files=[];for(const rel of stableEvidenceInventory(dir).map(x=>x.relativePath).concat(['manifests/final_manifest.json','manifests/SEALED.json'])){const src=path.join(dir,rel),dst=path.join(target,rel);const r=copyFileVerified(src,dst);files.push({relativePath:rel,...r})}if(COPY_ORIGINAL){const p=casePaths(dir);for(const n of fs.readdirSync(p.original)){const src=path.join(p.original,n);if(fs.statSync(src).isFile()){const rel='original/'+n;if(!files.some(x=>x.relativePath===rel))files.push({relativePath:rel,...copyFileVerified(src,path.join(target,rel))})}}}const receipt={schema:'chronoseal-export-receipt/v1',product:'PasevSU ChronoSeal Vault',exportedAt:now(),sourceCase:caseName,sourceSealSha512:readJson(path.join(casePaths(dir).manifests,'SEALED.json'),{}).sealSha512||null,files:files.map(x=>({relativePath:x.relativePath,bytes:x.bytes,sha256:x.sha256,sha512:x.sha512}))};writeJson(path.join(target,'EXPORT_RECEIPT.json'),receipt);return {ok:true,target,files:files.length,receiptSha512:shaBuf(canonicalBytes(receipt),'sha512')}}
async function finalizeCase(dir){if(isSealed(dir)){const v=verifySeal(dir);return v.ok?{ok:true,alreadySealed:true,sealed:readJson(path.join(casePaths(dir).manifests,'SEALED.json'),{}),verification:v}:{ok:false,error:'EXISTING_SEAL_INVALID',verification:v}};const preflight=await strictPreflight(dir);if(!preflight.ok)return {ok:false,error:'STRICT_PREFLIGHT_FAILED',preflight};const p=casePaths(dir),base=snapshotManifest(dir),final={...base,schema:'pasevsu-final-evidence-manifest/v4',preflight:{checkedAt:now(),original:preflight.original,ots:{primaryConfirmed:preflight.ots.primaryConfirmed,redundancyStatus:preflight.ots.redundancyStatus,bitcoinBlockHeights:preflight.ots.parsed.bitcoinBlockHeights},startTsa:{ok:preflight.start.ok,hashes:preflight.start.hashes},stopTsa:{ok:preflight.stop.ok,hashes:preflight.stop.hashes}},artifacts:stableEvidenceInventory(dir)},physical=verifyPhysicalArtifacts(dir,final.artifacts);if(!physical.ok)return {ok:false,error:'PRESEAL_PHYSICAL_INTEGRITY_FAILED',physical};const bytes=canonicalBytes(final),finalPath=path.join(p.manifests,'final_manifest.json');fs.writeFileSync(finalPath,bytes,{flag:'wx'});try{const fd=fs.openSync(finalPath,'r');fs.fsyncSync(fd);fs.closeSync(fd);fsyncDir(p.manifests)}catch{}const finalHash={sha256:shaBuf(bytes),sha512:shaBuf(bytes,'sha512'),bytes:bytes.length};audit(dir,'CASE_FINALIZED',finalHash);const postAudit=verifyAuditChain(dir);const sealCore={schema:'pasevsu-seal/v3',evidenceId:final.evidenceId,finalManifest:finalHash,auditHead:postAudit.head,auditEvents:postAudit.events,physicalArtifacts:final.artifacts.length,sealedAt:now()};const seal={...sealCore,sealSha512:shaBuf(canonicalBytes(sealCore),'sha512')};writeJson(path.join(p.manifests,'SEALED.json'),seal);try{fs.chmodSync(finalPath,0o444);fs.chmodSync(path.join(p.manifests,'SEALED.json'),0o444)}catch{}fsyncDir(p.manifests);const verified=verifySeal(dir);if(!verified.ok)return {ok:false,error:'POSTSEAL_VERIFICATION_FAILED',verification:verified};let exported=null;if(AUTO_EXPORT){try{exported=exportSealedCase(dir)}catch(e){return {ok:false,error:'AUTO_EXPORT_FAILED',message:e.message,sealed:seal}}}return {ok:true,sealed:seal,verification:verified,exported,preflight:{otsRedundancy:preflight.ots.redundancyStatus,startTsa:true,stopTsa:true,physicalArtifacts:final.artifacts.length}}}
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=canonicalize(v[k]);return o}return v}
function canonicalBytes(v){return Buffer.from(JSON.stringify(canonicalize(v)),'utf8')}
function writeCanonicalEvidenceManifest(dir){const p=casePaths(dir),orig=readJson(path.join(p.manifests,'original_manifest.json'),{}),state=readJson(p.state,{});const artifacts=inventory(dir).filter(x=>!x.path.startsWith('manifests/canonical_evidence_manifest')&&!x.path.endsWith('final_manifest.json')&&!x.path.startsWith('tsa/STOP/'));const core={schema:'pasevsu-canonical-evidence/v1',evidenceId:orig.evidenceId||null,original:{name:orig.originalName,bytes:orig.bytes,sha256:orig.sha256,sha512:orig.sha512},ots:{state:state.state||null,blockchain:state.blockchain||null},artifacts};const b=canonicalBytes(core),f=path.join(p.manifests,'canonical_evidence_manifest.json');fs.writeFileSync(f,b);return {file:f,relative:'manifests/canonical_evidence_manifest.json',sha256:shaBuf(b),bytes:b.length,core}}
function tsaConfig(){return {start:{id:'DFN',url:process.env.PASEVSU_TSA_START_URL||'https://zeitstempel.dfn.de/'},stop:{id:'DigiCert',url:process.env.PASEVSU_TSA_STOP_URL||'http://timestamp.digicert.com'}}}
async function tsaBridgeStart(dir){const p=casePaths(dir),c=writeCanonicalEvidenceManifest(dir),cfg=tsaConfig().start,out=path.join(p.tsa,'START');const r=await TSA.stamp({input:c.file,providerId:cfg.id,providerUrl:cfg.url,outdir:out,label:'RFC3161_START',caFile:CA_BUNDLE});const rec={schema:'pasevsu-tsa-start/v1',provider:cfg,canonicalManifest:{relative:c.relative,sha256:c.sha256,bytes:c.bytes},validation:r};writeJson(path.join(out,'START.json'),rec);audit(dir,r.ok?'TSA_START_VERIFIED':'TSA_START_FAILED',{provider:cfg.id,manifestSha256:c.sha256,ok:r.ok});refreshManifest(dir);return rec}
async function tsaBridgeStop(dir){const p=casePaths(dir),c=writeCanonicalEvidenceManifest(dir),start=readJson(path.join(p.tsa,'START','START.json'));if(!start?.validation?.ok)return {ok:false,error:'VERIFIED_START_TSA_REQUIRED'};const closing={schema:'pasevsu-closing-digest/v1',evidenceId:c.core.evidenceId,canonicalManifestSha256:c.sha256,startTokenSha256:start.validation.hashes?.tst||null,reportId:c.core.evidenceId,closingProvider:tsaConfig().stop.id};const b=canonicalBytes(closing),f=path.join(p.manifests,'closing_digest.json');fs.writeFileSync(f,b);const cfg=tsaConfig().stop,out=path.join(p.tsa,'STOP'),r=await TSA.stamp({input:f,providerId:cfg.id,providerUrl:cfg.url,outdir:out,label:'RFC3161_STOP',caFile:CA_BUNDLE});const rec={schema:'pasevsu-tsa-stop/v1',provider:cfg,closingDigest:{relative:'manifests/closing_digest.json',sha256:shaBuf(b),bytes:b.length,content:closing},validation:r};writeJson(path.join(out,'STOP.json'),rec);audit(dir,r.ok?'TSA_STOP_VERIFIED':'TSA_STOP_FAILED',{provider:cfg.id,closingDigestSha256:shaBuf(b),ok:r.ok});refreshManifest(dir);return rec}
function verifySeal(dir){
 const p=casePaths(dir),sealPath=path.join(p.manifests,'SEALED.json'),finalPath=path.join(p.manifests,'final_manifest.json');
 if(!exists(sealPath)||!exists(finalPath))return {ok:false,error:'SEAL_OR_FINAL_MANIFEST_MISSING'};
 const seal=readJson(sealPath),final=readJson(finalPath);if(!seal||!final)return {ok:false,error:'SEAL_OR_FINAL_MANIFEST_INVALID_JSON'};
 const fb=fs.readFileSync(finalPath),fh={bytes:fb.length,sha256:shaBuf(fb),sha512:shaBuf(fb,'sha512')};
 if(fh.bytes!==seal.finalManifest?.bytes||fh.sha256!==seal.finalManifest?.sha256||fh.sha512!==seal.finalManifest?.sha512)return {ok:false,error:'FINAL_MANIFEST_HASH_MISMATCH',expected:seal.finalManifest,actual:fh};
 const core={...seal};delete core.sealSha512;const calc=shaBuf(canonicalBytes(core),'sha512');if(calc!==seal.sealSha512)return {ok:false,error:'SEAL_HASH_MISMATCH',expected:seal.sealSha512,actual:calc};
 const auditCheck=verifyAuditChain(dir);if(!auditCheck.ok)return {ok:false,error:'AUDIT_CHAIN_INVALID',audit:auditCheck};if(auditCheck.head!==seal.auditHead||auditCheck.events!==seal.auditEvents)return {ok:false,error:'AUDIT_HEAD_MISMATCH',audit:auditCheck,sealAudit:{head:seal.auditHead,events:seal.auditEvents}};
 const physical=verifyPhysicalArtifacts(dir,final.artifacts);if(!physical.ok)return {ok:false,error:'PHYSICAL_ARTIFACT_INTEGRITY_FAILED',physical};
 return {ok:true,state:'SEALED_VERIFIED',finalManifest:fh,audit:auditCheck,physical};
}
function closureStatus(dir){const p=casePaths(dir),ots=readJson(p.state,{}),start=readJson(path.join(p.tsa,'START','START.json'),{}),stop=readJson(path.join(p.tsa,'STOP','STOP.json'),{});return {blockchainVerified:ots.state==='BLOCKCHAIN_VERIFIED',startTsaVerified:start.validation?.ok===true,stopTsaVerified:stop.validation?.ok===true,closed:ots.state==='BLOCKCHAIN_VERIFIED'&&start.validation?.ok===true&&stop.validation?.ok===true}}

function findCase(id){const clean=safeName(id);const d=path.join(CASE_ROOT,clean);return exists(d)&&fs.statSync(d).isDirectory()?d:null}
function canonicalize(value){
 if(Array.isArray(value))return value.map(canonicalize);
 if(value&&typeof value==='object'){const o={};for(const k of Object.keys(value).sort())o[k]=canonicalize(value[k]);return o}
 return value;
}
function canonicalJson(value){return JSON.stringify(canonicalize(value))}
function textHashSet(buf){
 const algs={md5:'md5',sha1:'sha1',sha224:'sha224',sha256:'sha256',sha384:'sha384',sha512:'sha512',sha3_224:'sha3-224',sha3_256:'sha3-256',sha3_384:'sha3-384',sha3_512:'sha3-512',ripemd160:'ripemd160'};
 const out={}; for(const [name,alg] of Object.entries(algs)){try{out[name]=crypto.createHash(alg).update(buf).digest('hex')}catch(e){out[name]=null}}
 return out;
}
function buildTextManifest(buf,meta={}){
 const hashes=textHashSet(buf), createdAt=now();
 const core={schema:'pasevsu-text-evidence-manifest/v1',evidenceType:'TEXT',createdAt,encoding:'UTF-8',normalization:'NONE_AFTER_API_BYTE_CAPTURE',byteLength:buf.length,hashes,context:{operation:String(meta.operation||'HASH_TIMESTAMP_MANIFEST'),source:String(meta.source||'user-input'),recipientFingerprint:meta.recipientFingerprint||null}};
 const canonical=canonicalJson(core), cb=Buffer.from(canonical,'utf8');
 return {manifest:{...core,manifestBinding:{canonicalization:'RFC8785-LIKE-SORTED-JSON-v1',sha256:shaBuf(cb),sha512:shaBuf(cb,'sha512')}},canonicalCore:canonical};
}
async function api(req,res,u){try{
 if(req.method==='GET'&&u.pathname==='/api/status')return j(res,200,status());
 if(req.method==='GET'&&u.pathname==='/api/case/status'){const d=findCase(u.searchParams.get('case')||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});return j(res,200,{ok:true,case:path.basename(d),state:readJson(casePaths(d).state),manifest:snapshotManifest(d)});}
 if(req.method==='GET'&&u.pathname==='/api/artifact'){const d=findCase(u.searchParams.get('case')||''),rel=String(u.searchParams.get('file')||'').replace(/\\/g,'/');if(!d||!rel||rel.includes('..')||rel.startsWith('/'))return j(res,400,{ok:false,error:'BAD_ARTIFACT_PATH'});const f=path.resolve(d,rel);if(!f.startsWith(path.resolve(d)+path.sep)||!exists(f)||!fs.statSync(f).isFile())return j(res,404,{ok:false,error:'ARTIFACT_NOT_FOUND'});res.writeHead(200,{'Content-Type':TYPES[path.extname(f).toLowerCase()]||'application/octet-stream','Content-Disposition':`attachment; filename="${path.basename(f).replace(/"/g,'')}"`,'Cache-Control':'no-store'});fs.createReadStream(f).pipe(res);return;}
 if(req.method==='POST'&&u.pathname==='/api/hash'){const h=await streamHash(req);return j(res,200,{...h,time:now()})}
 if(req.method==='POST'&&u.pathname==='/api/text/manifest'){
   const b=await body(req,16*1024*1024),m=buildTextManifest(b,{operation:req.headers['x-text-operation'],source:req.headers['x-text-source'],recipientFingerprint:req.headers['x-recipient-fingerprint']});
   return j(res,200,{ok:true,...m.manifest,canonicalCore:m.canonicalCore});
 }
 if(req.method==='POST'&&u.pathname==='/api/text/case'){
   const b=await body(req,16*1024*1024),m=buildTextManifest(b,{operation:req.headers['x-text-operation'],source:req.headers['x-text-source'],recipientFingerprint:req.headers['x-recipient-fingerprint']});
   const final={...m.manifest},bytes=Buffer.from(canonicalJson(final),'utf8'),name=safeName(req.headers['x-file-name']||`text_manifest_${Date.now()}.json`),c=makeCase(name,bytes);
   const tp=path.join(c.p.manifests,'text_evidence_manifest.json');fs.writeFileSync(tp,JSON.stringify(final,null,2));audit(c.dir,'TEXT_EVIDENCE_MANIFEST_CREATED',{textBytes:b.length,textHashes:m.manifest.hashes,manifestSha256:shaBuf(bytes)});refreshManifest(c.dir);
   return j(res,200,{ok:true,case:path.basename(c.dir),evidenceId:c.evidenceId,manifest:final,manifestSha256:shaBuf(bytes),manifestSha512:shaBuf(bytes,'sha512'),canonicalManifest:bytes.toString('utf8')});
 }

 if(req.method==='POST'&&u.pathname==='/api/ots/stamp'){const up=await streamToTemp(req),c=makeCaseFromTemp(req.headers['x-file-name'],up);assertWritable(c.dir);const work=path.join(c.p.ots,c.base),of=work+'.ots';fs.copyFileSync(c.dst,work);const r=await otsRun('stamp',work,of);if(!exists(of)){try{fs.unlinkSync(work)}catch{};audit(c.dir,'OTS_STAMP_FAILED',{result:r});refreshManifest(c.dir);return j(res,503,{...r,case:path.basename(c.dir),evidenceId:c.evidenceId,backupVerified:true,original:c.original,error:r.error||'OTS_NOT_CREATED'})}const oh=hashes(of);fs.unlinkSync(work);const st={schema:'pasevsu-ots-confirmation-state/v1',evidenceId:c.evidenceId,state:'CREATED',attempt:0,createdAt:now(),nextAttemptAt:now(),ots:{file:`ots/${path.basename(of)}`,...oh}};saveState(c.dir,st);audit(c.dir,'OTS_CREATED',{otsFile:path.basename(of),...oh});setImmediate(()=>withCaseLock(c.dir,()=>confirmationCycle(c.dir,true)).catch(console.error));return j(res,200,{ok:true,case:path.basename(c.dir),evidenceId:c.evidenceId,backupVerified:true,original:c.original,otsFile:path.basename(of),ots:oh,state:st.state,confirmationWorker:'STARTED',downloadUrl:`api/artifact?case=${encodeURIComponent(path.basename(c.dir))}&file=${encodeURIComponent('ots/'+path.basename(of))}`})}
 if(req.method==='POST'&&u.pathname==='/api/ots/upgrade'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);const r=await withCaseLock(d,()=>upgradeCase(d));return j(res,r.ok?200:(r.error==='CASE_BUSY_RETRY'?423:409),{...r,case:path.basename(d)})}
 if(req.method==='POST'&&u.pathname==='/api/ots/verify'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});const r=await withCaseLock(d,()=>verifyCase(d));return j(res,r.ok?200:(r.error==='CASE_BUSY_RETRY'?423:409),{...r,case:path.basename(d)})}
 if(req.method==='POST'&&u.pathname==='/api/ots/confirm-now'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);const state=await withCaseLock(d,()=>confirmationCycle(d,true));if(!state||state.ok===false)return j(res,409,{ok:false,case:path.basename(d),error:state?.error||'OTS_CONFIRMATION_NOT_EXECUTED',state});return j(res,200,{ok:true,case:path.basename(d),state})}
 if(req.method==='POST'&&u.pathname==='/api/case/artifact'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);return await withCaseLock(d,async()=>{const up=await streamToTemp(req),name=safeName(req.headers['x-file-name']),kind=safeName(req.headers['x-artifact-kind']||'artifacts').toLowerCase();const map={pgp:'signatures/pgp',xades:'signatures/xades',pades:'signatures/pades',report:'reports',artifact:'artifacts',artifacts:'artifacts'},rel=map[kind]||'artifacts',dest=path.join(d,rel,name);fs.mkdirSync(path.dirname(dest),{recursive:true});if(exists(dest)){const old=hashes(dest);try{fs.unlinkSync(up.tmp)}catch{};if(old.bytes===up.bytes&&old.sha256===up.sha256&&old.sha512===up.sha512)return j(res,200,{ok:true,idempotent:true,case:path.basename(d),file:`${rel}/${name}`,...old});return j(res,409,{ok:false,error:'ARTIFACT_NAME_COLLISION',case:path.basename(d),file:`${rel}/${name}`,existing:old,incoming:{bytes:up.bytes,sha256:up.sha256,sha512:up.sha512}})}atomicMoveNoReplace(up.tmp,dest);const h=hashes(dest);audit(d,'ARTIFACT_ADDED',{kind,file:`${rel}/${name}`,...h});const m=refreshManifest(d);return j(res,200,{ok:true,case:path.basename(d),file:`${rel}/${name}`,...h,manifestSha256:shaBuf(Buffer.from(canonicalJson(m))),artifactCount:m.artifacts.length})})}
 if(req.method==='POST'&&u.pathname==='/api/tsa/start'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);const r=await withCaseLock(d,()=>tsaBridgeStart(d));if(r.error==='CASE_BUSY_RETRY')return j(res,423,r);return j(res,r.validation?.ok?200:502,{ok:r.validation?.ok===true,case:path.basename(d),...r,closure:closureStatus(d)})}
 if(req.method==='POST'&&u.pathname==='/api/tsa/stop'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);const r=await withCaseLock(d,()=>tsaBridgeStop(d));if(r.error==='CASE_BUSY_RETRY')return j(res,423,r);return j(res,r.validation?.ok?200:409,{ok:r.validation?.ok===true,case:path.basename(d),...r,closure:closureStatus(d)})}
 if(req.method==='GET'&&u.pathname==='/api/case/audit-verify'){const d=findCase(u.searchParams.get('case')||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});const r=verifyAuditChain(d);return j(res,r.ok?200:409,r)}
 if(req.method==='GET'&&u.pathname==='/api/storage/status'){return j(res,200,{ok:true,storage:storageStatus()})}
 if(req.method==='GET'&&u.pathname==='/api/import/list'){try{return j(res,200,{ok:true,root:IMPORT_ROOT,recursive:IMPORT_RECURSIVE,files:listImportFiles()})}catch(e){return j(res,500,{ok:false,error:'IMPORT_SCAN_FAILED',message:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/import/case'){const rel=req.headers['x-import-path']||'';try{const r=importFileToCase(rel);return j(res,r.ok?200:(r.error==='IMPORT_FILE_NOT_FOUND'?404:409),r)}catch(e){return j(res,409,{ok:false,error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/case/export'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});try{const r=await withCaseLock(d,()=>exportSealedCase(d));return j(res,r.ok?200:409,r)}catch(e){return j(res,409,{ok:false,error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/case/finalize'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});const r=await withCaseLock(d,()=>finalizeCase(d));return j(res,r.ok?200:(r.error==='CASE_BUSY_RETRY'?423:409),r)}
 if(req.method==='POST'&&u.pathname==='/api/case/preflight-verify'){const d=findCase(req.headers['x-case-id']||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});const r=await withCaseLock(d,()=>strictPreflight(d));return j(res,r.ok?200:(r.error==='CASE_BUSY_RETRY'?423:409),r)}
 if(req.method==='GET'&&u.pathname==='/api/case/seal-verify'){const d=findCase(u.searchParams.get('case')||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});const r=verifySeal(d);return j(res,r.ok?200:409,{case:path.basename(d),...r})}
 if(req.method==='GET'&&u.pathname==='/api/case/closure'){const d=findCase(u.searchParams.get('case')||'');if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});return j(res,200,{ok:true,case:path.basename(d),closure:closureStatus(d)})}
 if(req.method==='POST'&&u.pathname==='/api/tsa/stamp'){const caseId=req.headers['x-case-id'];let c=null,d=null,inputCheck=null;if(caseId){d=findCase(caseId);if(!d)return j(res,404,{ok:false,error:'CASE_NOT_FOUND'});assertWritable(d);inputCheck=await streamHash(req)}else{const up=await streamToTemp(req);c=makeCaseFromTemp(req.headers['x-file-name'],up);d=c.dir;assertWritable(d)}const p=casePaths(d),orig=readJson(path.join(p.manifests,'original_manifest.json')),file=path.join(p.original,orig.originalName);if(inputCheck&&inputCheck.bytes&&inputCheck.sha256!==orig.sha256)return j(res,409,{ok:false,error:'INPUT_DOES_NOT_MATCH_CASE_ORIGINAL'});const label=safeName(req.headers['x-tsa-label']||'timestamp').replace(/\./g,'_'),providerId=String(req.headers['x-tsa-provider']||'DFN');const r=await withCaseLock(d,()=>TSA.stamp({input:file,providerId,providerUrl:req.headers['x-tsa-url']||undefined,outdir:path.join(p.tsa,label.toUpperCase()),label,caFile:CA_BUNDLE}));if(r.error==='CASE_BUSY_RETRY')return j(res,423,r);audit(d,r.ok?'TSA_CREATED':'TSA_FAILED',{label,ok:r.ok});refreshManifest(d);return j(res,r.ok?200:502,{...r,case:path.basename(d),evidenceId:orig.evidenceId})}

 return false;
 }catch(e){j(res,e.statusCode||500,{ok:false,error:e.message});return true}}
function safePath(pn){const raw=decodeURIComponent((pn||'/').split('?')[0]),rel=raw==='/'?'index.html':raw.replace(/^\/+/,''),p=path.resolve(ROOT,rel);return p.startsWith(path.resolve(ROOT)+path.sep)||p===path.resolve(ROOT)?p:null}
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://internal');if(u.pathname.startsWith('/api/')){const done=await api(req,res,u);if(done!==false)return}const p=safePath(u.pathname);if(!p)return res.writeHead(400).end('Bad path');fs.stat(p,(e,s)=>{if(e||!s.isFile())return res.writeHead(404).end('Not found');const ext=path.extname(p).toLowerCase();res.setHeader('Content-Type',TYPES[ext]||'application/octet-stream');res.setHeader('Cache-Control',ext==='.html'?'no-store':'private, max-age=3600');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'");fs.createReadStream(p).pipe(res)})}).listen(PORT,'0.0.0.0',()=>{console.log(`ChronoSeal Vault internal Ingress service on ${PORT}; cases=${CASE_ROOT}; export=${EXPORT_ROOT}`);worker();setInterval(worker,60*1000).unref()});
