'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process'),http=require('http'),https=require('https');
const PKI=require('../10-pgp/pki-engine.js');
const now=()=>new Date().toISOString();
const shaFile=(p,a='sha256')=>{const h=crypto.createHash(a),b=fs.readFileSync(p);return h.update(b).digest('hex')};
const cmd=(bin,args,opt={})=>new Promise(resolve=>cp.execFile(bin,args,{timeout:180000,maxBuffer:32*1024*1024,...opt},(error,stdout,stderr)=>resolve({ok:!error,code:error?.code??0,stdout:String(stdout||''),stderr:String(stderr||''),error:error?.message||null,command:[bin,...args]})));
const ALLOWED={DFN:new URL('https://zeitstempel.dfn.de/'),DigiCert:new URL('http://timestamp.digicert.com')};
function providerUrl(providerId,override){const base=ALLOWED[providerId];if(!base)throw Error('UNKNOWN_TSA_PROVIDER');if(!override)return base.toString();const u=new URL(override);if(u.hostname!==base.hostname||u.protocol!==base.protocol)throw Error('TSA_PROVIDER_OVERRIDE_NOT_ALLOWED');return u.toString()}
function postBinary(target,payload){return new Promise(resolve=>{let u;try{u=new URL(target)}catch{return resolve({ok:false,error:'INVALID_TSA_URL'})}if(!['https:','http:'].includes(u.protocol))return resolve({ok:false,error:'UNSUPPORTED_TSA_PROTOCOL'});const lib=u.protocol==='https:'?https:http;const q=lib.request({protocol:u.protocol,hostname:u.hostname,port:u.port||undefined,path:u.pathname+u.search,method:'POST',headers:{'Content-Type':'application/timestamp-query','Accept':'application/timestamp-reply','Content-Length':payload.length,'User-Agent':'PasevSU-HA-Evidence/1.0-rc4'}},r=>{const c=[];let n=0;r.on('data',x=>{n+=x.length;if(n>8*1024*1024)q.destroy(Error('TSA response too large'));else c.push(x)});r.on('end',()=>resolve({ok:r.statusCode>=200&&r.statusCode<300,status:r.statusCode,contentType:r.headers['content-type']||'',body:Buffer.concat(c)}))});q.on('error',e=>resolve({ok:false,error:e.message}));q.setTimeout(30000,()=>q.destroy(Error('TSA timeout')));q.end(payload)})}
function parseReply(t){const g=(re)=>String(t).match(re)?.[1]?.trim()||null;return {status:g(/Status:\s*([^\n]+)/i),policyOid:g(/Policy OID:\s*([^\n]+)/i),hashAlgorithm:g(/Hash Algorithm:\s*([^\n]+)/i),messageImprint:g(/Message data:\s*\n\s*([0-9A-Fa-f: ]+)/i)?.replace(/[: ]/g,'').toLowerCase()||null,serial:g(/Serial number:\s*([^\n]+)/i),genTime:g(/Time stamp:\s*([^\n]+)/i),nonce:g(/Nonce:\s*([^\n]+)/i)} }
async function stamp({input,providerId,providerUrl:override,outdir,label='timestamp',caFile='/etc/ssl/certs/ca-certificates.crt'}){fs.mkdirSync(outdir,{recursive:true});const url=providerUrl(providerId,override),tsq=path.join(outdir,`${label}.tsq`),tsr=path.join(outdir,`${label}.tsr`),tst=path.join(outdir,`${label}.tst`),txt=path.join(outdir,`${label}_response.txt`),verifyTxt=path.join(outdir,`${label}_verify.txt`);let q=await cmd('/usr/bin/openssl',['ts','-query','-data',input,'-sha256','-cert','-out',tsq]);if(!q.ok)return {ok:false,stage:'query',query:q};const net=await postBinary(url,fs.readFileSync(tsq));if(!net.ok)return {ok:false,stage:'request',network:{...net,body:undefined}};fs.writeFileSync(tsr,net.body);const reply=await cmd('/usr/bin/openssl',['ts','-reply','-in',tsr,'-text']);fs.writeFileSync(txt,reply.stdout+reply.stderr);if(!reply.ok)return {ok:false,stage:'reply_parse',reply};const token=await cmd('/usr/bin/openssl',['ts','-reply','-in',tsr,'-token_out','-out',tst]);const va=['ts','-verify','-queryfile',tsq,'-in',tsr,'-CAfile',caFile];const verify=await cmd('/usr/bin/openssl',va);fs.writeFileSync(verifyTxt,verify.stdout+verify.stderr);const parsed=parseReply(reply.stdout),expected=shaFile(input),imprintMatch=parsed.messageImprint?parsed.messageImprint===expected:null,mime=String(net.contentType).toLowerCase(),mimeOk=!mime||mime.includes('application/timestamp-reply')||mime.includes('application/timestamp-response')||mime.includes('application/octet-stream');const pki=token.ok?await PKI.validate({tst,outdir,providerId,caFile,genTime:parsed.genTime}):{ok:false,stage:'token-missing'};const strictOk=token.ok&&verify.ok&&imprintMatch===true&&mimeOk&&pki.ok;const result={schema:'pasevsu-rfc3161-validation/v2',ok:strictOk,createdAt:now(),providerId,providerUrl:url,httpStatus:net.status,contentType:net.contentType,mimeOk,input:{file:path.basename(input),sha256:expected},artifacts:{tsq:path.basename(tsq),tsr:path.basename(tsr),tst:token.ok?path.basename(tst):null,responseText:path.basename(txt),verifyText:path.basename(verifyTxt),pkiValidation:'RFC3161_PKI_VALIDATION.json'},hashes:{tsq:shaFile(tsq),tsr:shaFile(tsr),tst:token.ok?shaFile(tst):null},parsed,checks:{tokenExtracted:token.ok,queryResponseBinding:verify.ok,messageImprintMatch:imprintMatch,chainValidated:pki.checks?.chainValidated??false,pinnedRoot:pki.checks?.pinnedRoot??false,timeStampingEku:pki.checks?.timeStampingEku??false,ekuCritical:pki.checks?.ekuCritical??false,validAtGenTime:pki.checks?.validAtGenTime??false,revocationValidated:pki.checks?.revocationValidated??false,revoked:pki.checks?.revoked??null},pki,openssl:{query:q,reply,token,verify}};fs.writeFileSync(path.join(outdir,`${label}_validation.json`),JSON.stringify(result,null,2));return result}
async function validateExisting({input,outdir,label,providerId,caFile='/etc/ssl/certs/ca-certificates.crt'}){
 const tsq=path.join(outdir,`${label}.tsq`),tsr=path.join(outdir,`${label}.tsr`),tst=path.join(outdir,`${label}.tst`);
 if(!fs.existsSync(input)||!fs.existsSync(tsq)||!fs.existsSync(tsr)||!fs.existsSync(tst))return {ok:false,stage:'required-artifact-missing',required:{input,tsq,tsr,tst}};
 const reply=await cmd('/usr/bin/openssl',['ts','-reply','-in',tsr,'-text']);if(!reply.ok)return {ok:false,stage:'reply_parse',reply};
 const parsed=parseReply(reply.stdout),expected=shaFile(input),imprintMatch=parsed.messageImprint?parsed.messageImprint===expected:false;
 const verify=await cmd('/usr/bin/openssl',['ts','-verify','-queryfile',tsq,'-in',tsr,'-CAfile',caFile]);
 const pki=await PKI.validate({tst,outdir,providerId,caFile,genTime:parsed.genTime});
 const tokenHash=shaFile(tst),ok=verify.ok&&imprintMatch===true&&pki.ok===true;
 const result={schema:'pasevsu-rfc3161-revalidation/v1',ok,checkedAt:now(),providerId,input:{file:path.basename(input),sha256:expected},hashes:{tsq:shaFile(tsq),tsr:shaFile(tsr),tst:tokenHash},parsed,checks:{queryResponseBinding:verify.ok,messageImprintMatch:imprintMatch,pki:pki.ok===true},pki,openssl:{verify}};
 fs.writeFileSync(path.join(outdir,`${label}_revalidation.json`),JSON.stringify(result,null,2));return result;
}
module.exports={stamp,validateExisting,parseReply,ALLOWED};
